### ISSUE TITLE
Error running action

### ISSUE THREAD

**Issue by shoekstra** [stecky/yet-another-chart-releaser-action#1]
Hi @stecky,

I'm getting this error when trying to use the action: 

```shell
Run stecky/yet-another-chart-releaser-action@1.1.0
  with:
    charts_dir: helm-charts
    charts_repo_url: https://raw.githubusercontent.com/<org>/<repo>/gh-pages/
    packages_with_index: true
    version: 0.1.5
  env:
    YACR_TOKEN: ***
/home/runner/work/_temp/0f62d6d7-e33c-4a48-a92d-66dbf21af7df.sh: line 6: syntax error near unexpected token `)'
Error: Process completed with exit code 2.
```

Tried to replicate it locally but unable to, I was able to run it with this and not sure where it's going wrong in the action:

```
    ../yet-another-chart-releaser-action/yacr.sh --version 0.1.5 --owner <org> --repo <repo> --charts-dir helm-charts --packages-with-index true --charts-repo-url https://raw.githubusercontent.com/<org>/<repo>/gh-pages/
```

This is the config I used:

```yaml
      - name: Run chart-releaser
        uses: stecky/yet-another-chart-releaser-action@1.1.0
        with:
          charts_dir: helm-charts
          charts_repo_url: https://raw.githubusercontent.com/<org>/<repo>/gh-pages/
          packages_with_index: true
          version: 0.1.5
        env:
          YACR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

Any pointers would be helpful, would be great to use private GitHub Pages to host our charts.
